version: '3'

services:
    event-planner:
        build: .
        ports: 
            - "8081:8081"
        depends_on:
            - db
        container_name: event-planner


    db:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: insecure
        container_name: mysql-event-planner
