version: '3'

services:

    mysql-dev:
        image: mysql:8.0.2
        environment:
            MYSQL_ROOT_PASSWORD: insecure
            MYSQL_DATABASE: eventplanner
        ports:
            -"3306:3306"


